# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: MuleSoft
  - name: bronze_var
    value: $[if(variables['Build.SourceBranchName'], 'master', $(bronze_key))]


steps:
- task: DownloadSecureFile@1
  name: mySettings
  displayName: 'Download settings.xml'
  inputs:
    secureFile: 'settings.xml'

- bash: echo $(bronze_var)
  
